### PR TITLE
add TexiFyIDEA-based latex support

### PR DESCRIPTION
**Pull request by fberlakovich**
Adds support for the Latex language based on TexiFyIDEA (see https://github.com/Hannah-Sten/TeXiFy-IDEA). 

The language support leverages the `LatexPostfixExpressionSelector` from the TeXiFy IDEA project and configures it depending on the template keywords used. In particular, the language introduces the new keywords `MATH` and `TEXT`. The keywords specify that the template is only applicable in a Latex text context or math context, respectively. 

If you like the idea and are happy with the code, I can also update the README/wiki with the new keywords.

### CODE REVIEW

**Comment by xylo** [comment]
Your code looks good.  Thanks for adding LaTeX support. :)

**Comment by xylo** [comment]
If you like you can also edit the README and wiki. :)

**Comment by fberlakovich** [comment]
> If you like you can also edit the README and wiki. :)

Sure, will do!

**Comment by xylo** [comment]
Thanks. :)

**Pull request merged**
