### PR TITLE
use gradle to buildProject and fix python exception

### PR DESCRIPTION
**Pull request by gejun123456**

### CODE REVIEW

**Comment by xylo** [comment]
Oh, you added a gradle build file.  That's interesting.  Have to test if I can replace the current (complicated) configuration with that.

**Comment by xylo** [comment]
@gejun123456 Did you manage to run `gradle runIde`?
I always get an Exception when I try to do that.  Otherwise `gradle buildPlugin` works.

**Comment by gejun123456** [comment]
yes i can run it

what exception do you get

**Comment by xylo** [comment]
OK.  The problem was that I have a newer gradle version on my system and IDEA was using that instead of the project gradle version which is older.  And that led to some problems.

**Comment by xylo** [comment]
Thanks again for converting this project into a gradle project.  I'm very happy about that.  It simplifies the configuration for new developers/contributors A LOT.

**Comment by xylo** [comment]
I don't get it.  I thought gradle will unity and simplify the project configuration for new developers but I doubt it now.  I don't understand why it's that unstable.  For instance, when I checked out the project, I can run it with
`./gradlew buildProject runIde`
But I cannot run it with
`./gradlew runIde`
or with
`./gradlew clean buildProject runIde`

And it also looks like you can easily bring gralde into an inconsistent state so that you have to start over again to fix the project. :(

Moreover, after I managed to start the project from console I tried to do the same from IDEA but discover new problems.  I already managed to start it from IDEA once but now I cannot reproduce it anymore.  Damn.  It's a pitty that one cannot create plugin projects with maven.  Maven behaves at least deterministic.

**Comment by xylo** [comment]
I managed to run the plugin from IDEA now.  However, the IDEA instance that gets started looks corrupted.  It immediately throws an error that I shall report to the Google Android team and it does not open my sample project correctly (looks like the project view hangs during loading).  However, when I run the project from console I get the same error but the project loads correctly.

How did you start the plugin?  From IDEA or from console?

**Comment by xylo** [comment]
Moreover, when I use the compile button in IDEA the project fails to compile because of some lombok issues.  Does this work for you?

**Comment by gejun123456** [comment]
I'm staring the plugin from the IDEA,  i have met the lombok issue before, after I  Invalidate cache and restart, there is no error.   I also encounter the 
 Google Android error, it's might be the IDEA ultimate bounded Android Support plugin have conflict with Python plugin,  I guess we should remove dependency to python  in   plugins 'PythonCore:2018.3.183.4886.37'   I  will check about it.

invalidatecacheandrestart

**Comment by gejun123456** [comment]
After remove the plugin 'PythonCore:2018.3.183.4886.37'  part, the project can't compile.  I think the Android Support error is not important,  we might just ignore it now.

**Comment by xylo** [comment]
Thanks for the tips.  It works now for me, too.  Have to check if the plugin still works in the different IDEs now.

**Pull request merged**
