### PR TITLE
Add additional postfixes for python

### PR DESCRIPTION
**Pull request by Nachtalb**
There is not much to say about this, I do have a question though. Is it ok to add this to the current python template file? I am not sure because the files are named by the author via the `yaml` https://github.com/xylo/intellij-postfix-templates/blob/8b616fc1730679a7c9820fe6cd858b7a208093e8/templates/webTemplateFiles.yaml#L230-L231

### CODE REVIEW

**Comment by xylo** [comment]
Yeah, I named the file by the author because I don't want to give support for the python templates, since I don't use python.  Moreover, I think credits should go to the authors.

I don't want to make it too complicated but I also want to make it right.  So I see two options:
- You can either add your templates to bystrousak.stdlib.  In that case I would also add you to list of authors, but I'm not sure if I can add your email address, since the mailto:... function might not work afterwards:
https://github.com/xylo/intellij-postfix-templates/blob/8b616fc1730679a7c9820fe6cd858b7a208093e8/templates/webTemplateFiles.yaml#L233-L234
- You could also create your own templates file (which can be located in this repository but does not have to)

Which option do you prefer?

**Comment by Nachtalb** [comment]
Oops sorry i frogot to reply....

**Comment by xylo** [comment]
Sorry, yes I merged the code and wanted to add you as author, but somehow I got interrupted/distracted after the merging, so I forgot the rest.

Is it OK for you if I add your name (Nachtalb or Nick Espig?) to the list of authors? And your email address (that I took from https://nickespig.ch/) as well?

**Comment by Nachtalb** [comment]
If possible please use Nachtalb and info@nachtalb.ch

**Pull request merged**
